name: GitHub Actions Demo
on: [push]
jobs:
  Push-to-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: git config --global user.email "action@github.com"
      - run: git config --global user.name "GitHub Action"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: true

      - run: pnpm run export

      - name: Git add
        run: git add .

      - name: Git commit
        run: 'git commit -m "Github actions: update /docs"'

      - name: Git push
        run: 'git push origin main:main'
